### ISSUE TITLE
Sense Source Code

### ISSUE THREAD

**Issue by gcordalis** [oaeide/hello-sense-server#1]
I assume you've seen this, but cause it wasn't mentioned: they've released the source code. Should be a perfec starting point: https://github.com/hello

**Comment by oaeide** [comment]
I have not! They actually released it....I didn't actually believe they would. This is a perfect starting point indeed.

**Comment by gcordalis** [comment]
Let me know if you need a hand with anything. Happy to help if I can!

**Comment by ElectroGloop** [comment]
Not sure if you are aware, but a few of the backers from the kickstarter page for Sense have setup a slack page where they are discussing the source code linked above.
Definitely worth checking out!
https://join.slack.com/t/sensehello/shared_invite/enQtMzEwNTA3NDM5MDE1LWI0ZGM3YTQ4NDgwZGFiYWZkMjJiNDg3Y2M3NjM3Y2JjNmM0ODBhNTdhMjA4Y2YxNjhlYjlmN2UxMTEzMTE3YzI

**Comment by julian-cordes** [comment]
any news on this topic? want to pick up my sense again and use it
slack invite is no longer working :(

**Comment by dyslexicant** [comment]
Really interested in getting this up and running, would love to help but have no knowledge as of yet with coding. Going to be learning it pretty fast, any help required from my end, let me know. Would love to help get this running again ASAP.

**Comment by ghost** [comment]
@ElectroGloop could you send me, an invite link?

**Comment by cwd9** [comment]
@ElectoGloop can you send me an invite link ps i do know how to code a little bit and would love to help if i can

**Comment by gcordalis** [comment]
That slack group is mostly dead now - essentially it got to the point of having to reverse engineer the hardware to be able to install custom firmware. The server side of things will likely be trivial in comparison to the firmware management.

If anyone is interested in having a go first place to look is the firmware and hardware side of things.

**Comment by oaeide** [comment]
Hi. I'm sorry to say I haven't been able to focus much on this after the
initial repo.

Could you elaborate a bit on the need to change the FW? I was initially
thinking to avoid this by tricking the device to talk to locally hosted
server by local DNS or some networking tricks.

Den tor. 19. jul. 2018, 22:22 skrev George Cordalis <
notifications@github.com>:

**Comment by ghost** [comment]
@oaeide

That would not work, as we do not have the ability to crack the encryption ^^
So we need an customized firmware aka firmware with an new encryption that would be open to all developers
So we have 2 options, getting somebody involved who might be able to find an security hole or alter the firmware...

As for now, I do not have time to dig into the buildsystem they used (I'm no pro in arm systems, but it looks pretty awkward and very complicated) but when I have "semesterferien" (time between the semesters) I will try to figure out how it works, but it might not become my main task, as I am started learning Go(language not game) by programming some simple 2d games

**Comment by oaeide** [comment]
@d0narnbl1tz Or we could get the private key from Hello..... Don't know how likely that is, though. Has anyone looked in to what kind of encryption specifically we are talking about?

**Comment by gcordalis** [comment]
A while back someone from Hello joined the slack channel mentioned above and provided some insight, I don't think they (specifically) had access to a lot of this stuff after the company went under - I imagine some ex-employees do have these things backed up somewhere but will be a bit of a hunt to find the right person.

**Comment by Velociraptor85** [comment]
HI! so is this still alive? Also are you sure that the certificate and the chain is checked, one could maybe set up an self signed cert and test that? or what encryption are you thinking of? also if someone could invite me to that slack that would be nice ... would be happy to get that running too ^^

**Comment by MrTeal** [comment]
Hi, would like to mention that there was some activity a while ago in this git:
https://github.com/0ff/long-live-sense/issues/2

But it's been quiet ever since.

**Comment by darthlotus** [comment]
Cant someone edit app to run stand alone, so at least base features still work.
No login, no wifi, no server?

**Comment by jhoogeboom** [comment]
Is there still anything going on here? The slack channel invite is dead it seems. I've posted something on https://github.com/0ff/long-live-sense/issues/2  as well with a suggestion for flashing.

**Comment by Velociraptor85** [comment]
> Is there still anything going on here? The slack channel invite is dead it seems. I've posted something on [0ff/long-live-sense#2](https://github.com/0ff/long-live-sense/issues/2) as well with a suggestion for flashing.

So I would be in, but seems like there is nothing going on .. so sadly the sphere is something for the trash I fear :(

**Comment by jhoogeboom** [comment]
Still have to try it, but it seems the main mcu can just be flashed with edited firmware that contain edited endpoints.

**Comment by raipat** [comment]
just stumbled upon the hello release when searching for an obscure toolchain. I have a Sense device from back then... somewhere in a box... lol.
So if this takes off, I'm like to follow :)
good luck and bye

**Comment by MrTeal** [comment]
> Still have to try it, but it seems the main mcu can just be flashed with edited firmware that contain edited endpoints.

Love to hear if this works! Maybe I can use it as a sensor in home assistant 😁

**Comment by owarz** [comment]
check my repo. 

https://github.com/owarz/sense

**Comment by MrTeal** [comment]
> check my repo.
> 
> https://github.com/owarz/sense

Trying to get it installed using homebridge, but I'm having some troubles.

when using the terminal in homebridge:
```
homebridge-homebridge:/var/lib/homebridge $ npm install -g homebridge-sense-local
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/homebridge-sense-local - Not found
npm error 404
npm error 404  'homebridge-sense-local@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-11-28T10_29_02_256Z-debug-0.log
```

so then I tried installing it manually with adding the repo to node_modules:

```
homebridge-homebridge:/var/lib/homebridge/node_modules/sense-main $ npm install -g ./homebridge-sense-local

up to date in 452ms
```

But it doesn't show up in installed plugins after that.

Running npm run server gives:

```
homebridge-homebridge:/var/lib/homebridge/node_modules/sense-main $ npm run server
npm error Missing script: "server"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-11-28T10_31_33_104Z-debug-0.log
```

Edit:
I later tried installing it as follows:
```
homebridge-homebridge:/var/lib/homebridge/node_modules $ npm install -g https://github.com/owarz/sense.git

added 116 packages, and changed 1 package in 2m
```
But it still doesn't show up in plugins. 

And when running start from that folder:

```
homebridge-homebridge:/var/lib/homebridge/node_modules/sense-proxy $ npm start

> sense-proxy@1.0.0 start
> node src/server/index.js

node:internal/modules/cjs/loader:1252
  throw err;
  ^

Error: Cannot find module '../../storage'
Require stack:
- /homebridge/node_modules/sense-proxy/src/server/routes/v2/sensors.js
- /homebridge/node_modules/sense-proxy/src/server/index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/homebridge/node_modules/sense-proxy/src/server/routes/v2/sensors.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/homebridge/node_modules/sense-proxy/src/server/routes/v2/sensors.js',
    '/homebridge/node_modules/sense-proxy/src/server/index.js'
  ]
}

Node.js v22.11.0
```

Can you maybe tell me what I'm doing wrong?

Thanks in advance!

**Comment by owarz** [comment]
I think there's been a misunderstanding

first you will stand up the fake api server with docker container or  In a nodejs installed host, you will go to the src/server folder and run " npm install" , then "npm run server", after the server stands up and listening  80/443 , you will copy the homebridge-sense-local folder in the repo into the homebridge plugin folder and just say npm install. (I found it convenient to run it in the container.)

then you will enter conf into homebrige

{
    ‘platforms": [
        {
            ‘name": ‘Sense Device’,
            ‘email": ‘demo@example.com’,
            ‘password": ‘demo123’,
            ‘updateInterval": 10,
            ‘platform": ‘SenseLocal’
        }
    ]
}

The user password is not important here, the sense device gives auth ok no matter what password it comes with. 
it is not exactly a download and use repo, you need to set ports and local dns routing according to your environment.
by the way, I'm still developing. there are still a few problems, especially the protopuf messaging took a lot of time to solve

good luck

**Comment by MrTeal** [comment]
> I think there's been a misunderstanding
> 
> first you will stand up the fake api server with docker container or In a nodejs installed host, you will go to the src/server folder and run " npm install" , then "npm run server", after the server stands up and listening 80/443 , you will copy the homebridge-sense-local folder in the repo into the homebridge plugin folder and just say npm install. (I found it convenient to run it in the container.)
> 
> then you will enter conf into homebrige
> 
> { ‘platforms": [ { ‘name": ‘Sense Device’, ‘email": ‘[demo@example.com](mailto:demo@example.com)’, ‘password": ‘demo123’, ‘updateInterval": 10, ‘platform": ‘SenseLocal’ } ] }
> 
> The user password is not important here, the sense device gives auth ok no matter what password it comes with. it is not exactly a download and use repo, you need to set ports and local dns routing according to your environment. by the way, I'm still developing. there are still a few problems, especially the protopuf messaging took a lot of time to solve
> 
> good luck

Thanks for your reply, and not to mention awesome that you got it running this far! Thanks for that, I had given up on ever getting it to be useful again.

I have local dns rewrite setup already, just have some problems getting the server up (also in docker it says it's missing things)

```
}
  ]
    '/app/src/server/index.js'
    '/app/src/server/routes/v2/sensors.js',
  requireStack: [
  code: 'MODULE_NOT_FOUND',
    at Module.require (node:internal/modules/cjs/
    at Function.Module._load (node:internal/modules/cjs/
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Object.Module._extensions..js (node:internal/modules/cjs
    at Module._compile (node:internal/modules/cjs/
    at Object.<anonymous> (/app/src/server/routes/v2/
    at require (node:internal/modules/cjs/helpers:119:18)
    at Module.require (node:internal/modules/cjs/
    at Function.Module._load (node:internal/modules/cjs/
    at Function.Module._resolveFilename (node:internal/modules/
- /app/src/server/index.js
- /app/src/server/routes/v2/sensors.js
Require stack:
Error: Cannot find module '../../storage'

  ^
  throw err;
node:internal/modules/cjs/loader:1031
```

I'll fiddle around with it a bit see if I can get it going. Keep up the good work!

**Comment by owarz** [comment]
thank you :)

please try  , docker compose up --build

send me the error printout and I will review it again.

I also ask you to write in the issue section of the repo.

**Comment by MrTeal** [comment]
> thank you :)
> 
> please try , docker compose up --build
> 
> send me the error printout and I will review it again.
> 
> I also ask you to write in the issue section of the repo.

I did update the docker compose to add the volume for storage, still get the error. will also add this to the issue of the repo.

docker-compose file:

```
version: '3.8'

services:
  sense-api:
    build: .
    container_name: sense-api
    ports:
      - "80:80"
    volumes:
      - ./storage:/app/storage  # Mount the local 'storage' folder into the container
    networks:
      - sense_network

networks:
  sense_network:
    name: sense_network

```

```
docker-compose up --build
WARN[0000] sense-main/docker-compose.yml: `version` is obsolete 
[+] Building 2.8s (11/11) FINISHED                                                                        docker:desktop-linux
 => [sense-api internal] load build definition from Dockerfile                                                            0.0s
 => => transferring dockerfile: 343B                                                                                      0.0s
 => [sense-api internal] load metadata for docker.io/library/node:16-alpine                                               1.1s
 => [sense-api internal] load .dockerignore                                                                               0.0s
 => => transferring context: 2B                                                                                           0.0s
 => [sense-api 1/6] FROM docker.io/library/node:16-alpine@sha256:a1f9d027912b58a7c75be7716c97cfbc6d3099f3a97ed84aa490be9  0.0s
 => [sense-api internal] load build context                                                                               0.0s
 => => transferring context: 215.29kB                                                                                     0.0s
 => CACHED [sense-api 2/6] WORKDIR /app                                                                                   0.0s
 => CACHED [sense-api 3/6] RUN mkdir -p /app/storage                                                                      0.0s
 => [sense-api 4/6] COPY package*.json ./                                                                                 0.0s
 => [sense-api 5/6] RUN npm install --production                                                                          1.5s
 => [sense-api 6/6] COPY src/ ./src/                                                                                      0.0s
 => [sense-api] exporting to image                                                                                        0.1s
 => => exporting layers                                                                                                   0.1s
 => => writing image sha256:a8e4c03d315864ea4e184e9f7dccb38d8dba2ffe035af951b3f5e95af46a09ef                              0.0s
 => => naming to docker.io/library/sense-main-3-sense-api                                                                 0.0s
[+] Running 1/1
 ✔ Network sense_network  Created                                                                                         0.0s 
 ⠋ Container sense-api    Created                                                                                         0.0s 
Attaching to sense-api
sense-api  | node:internal/modules/cjs/loader:1031
sense-api  |   throw err;
sense-api  |   ^
sense-api  | 
sense-api  | Error: Cannot find module '../../storage'
sense-api  | Require stack:
sense-api  | - /app/src/server/routes/v2/sensors.js
sense-api  | - /app/src/server/index.js
sense-api  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
sense-api  |     at Function.Module._load (node:internal/modules/cjs/loader:873:27)
sense-api  |     at Module.require (node:internal/modules/cjs/loader:1100:19)
sense-api  |     at require (node:internal/modules/cjs/helpers:119:18)
sense-api  |     at Object.<anonymous> (/app/src/server/routes/v2/sensors.js:3:17)
sense-api  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
sense-api  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
sense-api  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
sense-api  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
sense-api  |     at Module.require (node:internal/modules/cjs/loader:1100:19) {
sense-api  |   code: 'MODULE_NOT_FOUND',
sense-api  |   requireStack: [
sense-api  |     '/app/src/server/routes/v2/sensors.js',
sense-api  |     '/app/src/server/index.js'
sense-api  |   ]
sense-api  | }
sense-api exited with code 1
```

**Comment by owarz** [comment]
I'm fixing it. I'll push it soon.

**Comment by josephspurrier** [comment]
## Getting a Sense to talk to a self-hosted server, end-to-end (2026)

Managed to get a Hello Sense (firmware 1.3.0, build 4513) fully uploading sensor data to a local server over its own WiFi + HTTPS path, the same way it once talked to Hello's cloud. Sharing the full method and the non-obvious gotchas, since several of them aren't in the released source.

### 1. Hardware access (UART + CC3200 bootloader)
- The micro-USB connector carries the CC3200 UART. Pin 4 (ID) selects the mode: **ID→GND = debug console** (app runs, 115200 8N1), **ID→high = CC3200 UART bootloader**.
- **Critical gotcha: drive the signals at 3.3V, not 5V.** Power VBUS from 5V, but TX/RX/ID must be 3.3V. At 5V, `cc3200tool`'s `SWITCH_2_APPS` (NWP bootloader handoff) silently fails; at 3.3V it works and you get full SimpleLink flash read/write.

### 2. Recovering the AES key
- All HTTP messages are AES-128-CBC signed. Each device has a **unique 16-byte key at `/cert/key.aes`** (falls back to `1234567891234567` if absent). It's binary, not guessable.
- Read it directly with `cc3200tool ... read_file /cert/key.aes key.aes` (in the bootloader, 3.3V). Full FS read/write also lets you back up everything first.
- Signing scheme: request = `protobuf + IV(16) + AES-CBC(SHA1(body) padded to 32B)`; response mirrors it.

### 3. DNS redirect
- Endpoints are hardcoded `*.hello.is` (`sense-in.hello.is` `/in/sense/batch` + `/in/sense/state`, `messeji.hello.is`, `time.hello.is`; dev variants `dev-in.hello.is` / `messeji-dev.hello.is`, selected by the file `/hello/dev` via the `setDev` command). No need to change them — just run a DNS server that answers `*.hello.is` with your server's IP and point the device's DNS at it.

### 4. The TLS wall (the hard part)
The Sense's ClientHello offers **only `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA` (0xC014)** and sends **no `supported_groups` extension**. Modern TLS stacks (OpenSSL 3.x, LibreSSL 2.8.3, Go 1.26) all reject this with `NO_SHARED_CIPHER` — they refuse to pick an ECDHE curve without the extension. The original Hello servers ran old OpenSSL 1.0.x, which defaulted to P-256.
- **Fix: terminate TLS with `tlslite-ng` (pure Python)**, which assumes P-256 when the extension is absent. (Also needed a one-line patch: tlslite's `recv_into` returns `None` at EOF, which crashes `http.server`; make it return `0`.)

### 5. Cert trust + the date bug
- The device validates the server cert against `/cert/ca.der`. Generate your own CA, sign a server cert (CN `*.hello.is` + SANs for each host), and write your CA to `/cert/ca.der` with `cc3200tool write_file`.
- **The device's clock runs ~70 years behind** (a firmware epoch bug: real 2026 shows as 1956). Cert date validation therefore fails (`sl_Connect` error **-461 = `SL_ESECDATEERROR`**) unless the cert's `notBefore` is **before ~1956**. Generate the cert valid from **1950** and it passes.

### Result
Sensor batches decode cleanly: temperature, humidity, light, dust.

### Still open
- Our server replies to `/in/sense/batch` with a plain 200; the device wants a **signed** response (IV+sig) and resends until it gets one, so readings repeat rather than advancing. The `sign_response` used for time sync should apply here too.
- Logged timestamps read ~1956 due to the epoch bug (values are correct); trivially corrected server-side.

**Comment by josephspurrier** [comment]
### Hardware + physical assembly notes

Parts used:
- **Micro-USB male breakout board** — [Treedix USB MicroB Plug Breakout Board (B09JC7JPGN)](https://www.amazon.com/dp/B09JC7JPGN) — plugs into the Sense's port and breaks out VBUS / D- / D+ / ID / GND.
- **3.3V-capable USB-UART adapter** — [FT232 USB-UART board, FT232RL, 5V/3.3V (B0CSYVXH8L)](https://www.amazon.com/dp/B0CSYVXH8L) — the 3V3/5V jumper is important (see below).

**Getting the breakout to physically fit the Sense's port:** the micro-USB connector is recessed, so to seat the breakout you have to partially disassemble the sphere:
1. Remove the **4 screws on the bottom**.
2. Remove the screws holding the **light ring** and the **internal board**, so the board lifts enough for the breakout to plug into the micro-USB port.

**Wiring (FT232 adapter ↔ micro-USB breakout):**
- FT232 voltage jumper → **3.3V**. The CC3200 is **not** 5V-tolerant on its I/O, and 5V also silently breaks the bootloader handoff (`SWITCH_2_APPS`).
- Breakout `VBUS` → FT232 **5V** pin (raw USB 5V — this powers the Sense).
- Breakout `GND` → FT232 `GND`.
- Breakout `D+` → FT232 `TXD`, `D-` → FT232 `RXD` — **note: D+ and D- are swapped on this breakout, so if you get no console output, swap these two.**
- Breakout `ID`:
  - → `GND` = **debug console** (device boots normally, 115200 8N1)
  - → FT232 `RTS` = **CC3200 bootloader** (then run `cc3200tool -p <port> --reset none --sop2 '~rts' ...`)

Keep VBUS at 5V for power, everything else at 3.3V, and share a common ground.

**Comment by josephspurrier** [comment]
All the Hello Sense software has been consolidated and iOS app code submitted here for a fully working independent system: https://github.com/josephspurrier/hello-sense. Thanks all for the info on making this possible.
